{% set name = "datamountaineer-schemaregistry" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datamountaineer-schemaregistry-{{ version }}.tar.gz
  sha256: 15ac3c28499322f3d68454f276d4b64745b835fddd78919f1210ff44f8d48345

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - fastavro
    - avro-python3

test:
  imports:
    - datamountaineer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/datamountaineer/python-serializers
  license: Apache-2.0
  license_file: LICENSE
  summary: 'DataMountaineer Python 3.5 Confluent Schema Registry Client'
  license_family: Apache

extra:
  recipe-maintainers:
    - kwilcox
