travis:
  secure:
    BINSTAR_TOKEN: z0XJyJ4D2xIiXz8OSDXM2SB+rXFG2c+9ZA02ahI9pkKLamFsqcEit5Yw9Inomq4dKKZWulXBcb1MrQ/Gv90BoFEqc3ijqgi6QCTDx6CUNYYPaeU0iH3JLfpyn/RdFnD8KCqVR5TnHEuT153aem2pnqfo1cBNyu3gMLegi/GTub2JcX0i8gMeOqeHGyi8KBmzftSIccZUMrz1DNQK2ERW5nDYGgGftVuKi+Jf8xYe2+0+v0AhLVgTE9WYZ5KBit2QnwKNg6SRjD14skCmRgGlrpXp1TceGAKJ7p/1XOD69AGvZ6G3s+MhQd8mryOP5WdGLrE7ntfpseJnwyYR7R+yBNLPHjj7VSSdIR1TM1Hspho7UQY8/aspFNGUxzzBLApOwgZ9KcJQFH4/gDRlcr5Dq05JBKqJsf4WtMaZ9dPhIvbfUGCNALkLI42nC46+Cvxuuj+VHnFCOhBdJlzn1spCtpBBC3GJjZWUMrQq3rRSK+smi1Tx8UDhHfERHQ2LYTQq32x9+hsZJBnXVVGbVuKdBKF3e9jLusryjKHqQqu6NmxslOCpv+0lyYbvjvcFPdN6E3XH2FRD0qfeWWb6VRIbj/hxr9cM8FfG48V/FlVarwCV9HBw3CD3d5N37pDesWAc4eaL5iQ0RRro9CC4E6M1c0uDnjxM4ehbJ9sNOWughuI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
